controllers/PhotoController.php
<?php

namespace app\controllers;

use app\models\PhotoRating;
use app\models\PhotoTag;
use app\models\Tag;
use Yii;
use app\models\Photo;
use app\models\PhotoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PhotoController implements the CRUD actions for Photo model.
 */
class PhotoController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Photo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PhotoSearch();
        $params = Yii::$app->request->queryParams;
        $params[$searchModel->formName()]['created_by'] = Yii::$app->user->id;
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Photo model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Photo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Photo();

        if ($model->load(Yii::$app->request->post())) {

            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');

            if ($model->imageFile) {
                $model->upload();
            }

            if ($model->save()) {

                $this->assignTags($model);

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Photo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        foreach ($model->assignedTags as $assignedTag) {
            $model->tags .= $assignedTag->tag->name . ', ';
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $this->assignTags($model);

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Photo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Photo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Photo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Photo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function assignTags($model)
    {

        PhotoTag::deleteAll(['photo_id' => $model->id]);

        $arTags = explode(',', $model->tags);

        foreach ($arTags as $tag) {
            $tag = trim($tag);

            if (strlen($tag)) {

                $modelTag = Tag::find()->where(['name' => $tag])->one();
                if ($modelTag !== null) {
                    $modelPhotoTag = new PhotoTag();
                    $modelPhotoTag->photo_id = $model->id;
                    $modelPhotoTag->tag_id = $modelTag->id;
                    $modelPhotoTag->save();
                } else {
                    $modelTag = new Tag();
                    $modelTag->name = $tag;

                    if ($modelTag->save()) {
                        $modelPhotoTag = new PhotoTag();
                        $modelPhotoTag->photo_id = $model->id;
                        $modelPhotoTag->tag_id = $modelTag->id;
                        $modelPhotoTag->save();
                    }
                }
            }
        }
    }

    public function actionRating($id, $value)
    {

        $value = intval($value) > 0 ? $value : 1;
        $model = $this->findModel($id);
        if ($model === null) {
            return false;
        }

        if (Yii::$app->user->isGuest) {
            $this->goHome();
        }

        $modelPhotoRating = PhotoRating::find()->where(['photo_id' => $id, 'user_id' => Yii::$app->user->id])->one();

        if ($modelPhotoRating !== null) {
            return;
        } else {
            $modelPhotoRating = new PhotoRating();
            $modelPhotoRating->photo_id = $id;
            $modelPhotoRating->user_id = Yii::$app->user->id;
            $modelPhotoRating->rating = $value;

            if ($modelPhotoRating->save()) {
                $model->count_votes += 1;
                $model->total_rating += $value;
                $model->rating = round($model->total_rating / $model->count_votes,  1);
                $model->save();
            }
        }
        return true;
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\bootstrap4\Breadcrumbs;
use app\assets\AppAsset;
use app\models\Tag;

/*Yii::$app->assetManager->bundles = [
    'yii\bootstrap\BootstrapPluginAsset' => false,
    'yii\bootstrap\BootstrapAsset' => false
];*/

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<?php
NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar navbar-dark bg-dark navbar-expand-lg',
    ],
]);

$menuItems = [
    ['label' => 'Главная', 'url' => ['/site/index']],
    ['label' => 'О проекте', 'url' => ['/site/about']]
];

if (Yii::$app->user->isGuest) {
    $menuItems[] = ['label' => 'Авторизация', 'url' => ['/site/login']];
    $menuItems[] = ['label' => 'Регистрация', 'url' => ['/site/signup']];
} else {
    $menuItems[] = '<li class="nav-item">'
        . Html::beginForm(['/site/logout'], 'post')
        . Html::submitButton(
            'Выйти (' . Yii::$app->user->identity->username . ')',
            ['class' => 'btn btn-link nav-link']
        )
        . Html::endForm()
        . '</li>';
}

echo Nav::widget([
    'options' => ['class' => 'navbar-nav ml-auto'],
    'items' => $menuItems
]);
NavBar::end();
?>

<main role="main">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-9">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
            <div class="col-12 col-sm-3">
                <? if (!Yii::$app->user->isGuest): ?>
                    <?= Html::a('Добавить изображение', ['/photo/create'], ['class' => 'btn btn-primary mb-2']) ?>
                    <?= Html::a('Мои изображения', ['/photo/index'], ['class' => 'btn btn-primary']) ?>
                <? endif; ?>
                <br/>
                Теги:<br/>
                <?
                $arTags = \yii\helpers\ArrayHelper::map(Tag::find()->all(), 'id', 'name');
                foreach ($arTags as $id => $tag) { ?>
                    <a href="/?PhotoSearch[tag]=<?= $id; ?>" class="btn btn-outline-primary mb-1"><?= $tag; ?></a>
                <? } ?>
            </div>
        </div>
    </div>
</main>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Dev 2019</p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<? /*<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer*/ ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>